import pandas as pd
import numpy as np
from scipy.stats import linregress
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
import xgboost as xgb
import lightgbm as lgb
import warnings

# Suppress warnings for cleaner output
warnings.filterwarnings('ignore')

# --- 1. CONFIGURATION ---
SHIFT = 7  # The Golden Key
N_FOLDS = 5
SEED = 42

# Define the models for the Ensemble
def get_ensemble_models():
    # 1. XGBoost (The Gradient Boosting King)
    xgb_clf = xgb.XGBClassifier(
        n_estimators=500,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        n_jobs=-1,
        random_state=SEED,
        eval_metric='mlogloss'
    )
    
    # 2. LightGBM (Fast and accurate)
    lgb_clf = lgb.LGBMClassifier(
        n_estimators=500,
        num_leaves=31,
        max_depth=-1,
        learning_rate=0.05,
        n_jobs=-1,
        random_state=SEED,
        verbose=-1
    )
    
    # 3. Random Forest (The Stabilizer - different math than Boosting)
    rf_clf = RandomForestClassifier(
        n_estimators=300,
        max_depth=10,
        min_samples_leaf=4,
        n_jobs=-1,
        random_state=SEED,
        class_weight='balanced' 
    )
    
    # Combine into a Voting Classifier (Soft Voting averages probabilities)
    ensemble = VotingClassifier(
        estimators=[
            ('xgb', xgb_clf),
            ('lgb', lgb_clf),
            ('rf', rf_clf)
        ],
        voting='soft'
    )
    return ensemble

# --- 2. ADVANCED FEATURE ENGINEERING ---
def calculate_trend(series):
    """Calculates the slope (trend) of the last window."""
    # We use a simple linear regression on the values to find the slope
    # If slope > 0, traffic is increasing.
    try:
        slope, _, _, _, _ = linregress(range(len(series)), series)
        return slope
    except:
        return 0.0

def feature_engineering(df):
    print(f"   -> Engineering features for {len(df)} rows...")
    
    # A. Time Features
    if 'video_time' in df.columns:
        dt = pd.to_datetime(df['video_time'], errors='coerce')
        hour = dt.dt.hour.fillna(12)
        # Cyclical encoding
        df['hour_sin'] = np.sin(2 * np.pi * hour / 24)
        df['hour_cos'] = np.cos(2 * np.pi * hour / 24)
    else:
        df['hour_sin'] = 0
        df['hour_cos'] = 0

    # B. Physics Interactions
    # Jam Factor: Density * Stop Ratio
    df['jam_factor'] = df['mean_vehicle_count'] * df['stop_ratio']
    # Flow Index: Count / (Displacement + epsilon)
    df['flow_index'] = df['mean_vehicle_count'] / (df['mean_displacement'] + 1.0)

    # C. "ARIMA-lite" Trend Features
    # Calculate the slope of vehicle count for each camera segment
    # (Group by Camera and ID to process the 15-min chunks if possible, 
    # but here we operate on rows. Ideally, rolling slope is better)
    # Since we have rolling features, let's add specific Rolling Slopes if possible
    # For speed, we will rely on Delta features created below.
    
    # D. Lags and Rolling Stats (The heavy lifters)
    # We apply this per Camera
    df = df.sort_values(by=['Camera', 'time_segment_id'])
    
    cols_to_roll = ['mean_vehicle_count', 'stop_ratio', 'flow_imbalance']
    for col in cols_to_roll:
        grp = df.groupby('Camera')[col]
        
        # Trends
        df[f'{col}_roll_mean_5'] = grp.rolling(5, min_periods=1).mean().reset_index(0, drop=True)
        
        # Momentum (Delta)
        df[f'{col}_lag_1'] = grp.shift(1)
        df[f'{col}_delta_1'] = df[col] - df[f'{col}_lag_1']
        
        # Acceleration (Delta of Delta)
        df[f'{col}_accel'] = df[f'{col}_delta_1'] - df[f'{col}_delta_1'].shift(1)

    # Fill NaNs generated by lags
    df = df.fillna(0)

    # Camera Encoding
    cam_map = {"Norman Niles #1": 1, "Norman Niles #2": 2, "Norman Niles #3": 3, "Norman Niles #4": 4}
    if 'Camera' in df.columns:
        df['camera_code'] = df['Camera'].map(cam_map).fillna(0)
        
    return df

# --- 3. TRAINING PIPELINE ---
def train_and_predict(target_name, train_df, test_df, feature_cols):
    print(f"\n=== Training Ensemble for Target: {target_name} ===")
    
    # Prepare Labels
    label_map = {"free flowing": 0, "light delay": 1, "moderate delay": 2, "heavy delay": 3}
    reverse_map = {v: k for k, v in label_map.items()}
    
    # Create Lagged Target (The Forecast)
    # Sort to ensure alignment
    train_df.sort_values(by=['Camera', 'time_segment_id'], inplace=True)
    
    # Map text to int
    train_df['target_temp'] = train_df[target_name].map(label_map)
    
    # SHIFT: Input T -> Target T+7
    train_df['target_future'] = train_df.groupby('Camera')['target_temp'].shift(-SHIFT)
    
    # Clean training data
    train_clean = train_df.dropna(subset=['target_future']).copy()
    
    X = train_clean[feature_cols]
    y = train_clean['target_future'].astype(int)
    X_test = test_df[feature_cols]

    # Impute
    imputer = SimpleImputer(strategy='median')
    X_imputed = imputer.fit_transform(X)
    X_test_imputed = imputer.transform(X_test)
    
    # Cross-Validation Storage
    oof_preds = np.zeros((len(X), 4)) # Out of Fold predictions
    test_preds_accum = np.zeros((len(X_test), 4)) # Test predictions accumulator
    
    skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
    
    for fold, (train_idx, val_idx) in enumerate(skf.split(X_imputed, y)):
        X_tr, y_tr = X_imputed[train_idx], y.iloc[train_idx]
        X_val, y_val = X_imputed[val_idx], y.iloc[val_idx]
        
        # Get Fresh Ensemble
        model = get_ensemble_models()
        model.fit(X_tr, y_tr)
        
        # Predict Probabilities
        val_probs = model.predict_proba(X_val)
        test_probs = model.predict_proba(X_test_imputed)
        
        # Accumulate
        test_preds_accum += test_probs
        
        # Score
        acc = model.score(X_val, y_val)
        print(f"   Fold {fold+1} Accuracy: {acc:.4f}")

    # Average Test Predictions
    avg_test_probs = test_preds_accum / N_FOLDS
    final_classes = np.argmax(avg_test_probs, axis=1)
    
    # Convert back to strings
    return [reverse_map[c] for c in final_classes]

def main():
    print("--- Loading Data ---")
    try:
        path = "../data/"
        train_feats = pd.read_csv(path + 'cv_features_train_ready.csv')
        test_feats = pd.read_csv(path + 'cv_features_test_ready.csv')
        train_labels = pd.read_csv(path + 'Train.csv')
        test_meta = pd.read_csv(path + 'TestInputSegments.csv')
        sample_sub = pd.read_csv(path + 'SampleSubmission.csv')
    except:
        train_feats = pd.read_csv('cv_features_train_ready.csv')
        test_feats = pd.read_csv('cv_features_test_ready.csv')
        train_labels = pd.read_csv('Train.csv')
        test_meta = pd.read_csv('TestInputSegments.csv')
        sample_sub = pd.read_csv('SampleSubmission.csv')

    # Prep
    train_labels.rename(columns={'view_label': 'Camera'}, inplace=True)
    if 'view_label' in test_meta.columns: test_meta.rename(columns={'view_label': 'Camera'}, inplace=True)

    # Merge
    train_df = pd.merge(train_feats, train_labels, on=['time_segment_id', 'Camera'], how='inner')
    test_df = pd.merge(test_feats, test_meta, on=['time_segment_id', 'Camera'], how='left')

    # Feature Engineering
    print("--- Feature Engineering ---")
    train_df = feature_engineering(train_df)
    test_df = feature_engineering(test_df)

    # Select Features (Numeric only)
    exclude = ['camera_id', 'video_file', 'clean_filename', 'Camera', 
               'congestion_enter_rating', 'congestion_exit_rating',
               'target_future', 'time_segment_id', 'minute', 'ID',
               'dt', 'video_time', 'videos', 'date', 'datetimestamp_start', 'datetimestamp_end',
               'responseId', 'ID_enter', 'ID_exit', 'signaling', 'cycle_phase', 'target_temp']
    
    feature_cols = [c for c in train_df.columns if c not in exclude and np.issubdtype(train_df[c].dtype, np.number)]
    print(f"Features ({len(feature_cols)}): {feature_cols}")

    # --- PIPELINE 1: ENTER RATING ---
    enter_preds = train_and_predict("congestion_enter_rating", train_df, test_df, feature_cols)
    
    # --- PIPELINE 2: EXIT RATING ---
    # CRITICAL STEP: We repeat the entire process for the Exit Target
    exit_preds = train_and_predict("congestion_exit_rating", train_df, test_df, feature_cols)

    # --- SUBMISSION GENERATION ---
    print("\n--- Constructing Final Submission ---")
    
    # Map predictions to IDs
    # Remember: Input T predicts T+7
    test_df['predicted_id'] = test_df['time_segment_id'] + SHIFT
    
    # Create a lookup dictionary for both Enter and Exit
    preds_map = {}
    
    for i, row in test_df.iterrows():
        # ID Construction
        # 1. Enter ID
        ent_id = f"time_segment_{int(row['predicted_id'])}_{row['Camera']}_congestion_enter_rating"
        preds_map[ent_id] = enter_preds[i]
        
        # 2. Exit ID
        ext_id = f"time_segment_{int(row['predicted_id'])}_{row['Camera']}_congestion_exit_rating"
        preds_map[ext_id] = exit_preds[i]

    # Fill Sample Submission
    final_rows = []
    for rid in sample_sub['ID'].values:
        # Default to 'free flowing' if not found (e.g. edge cases)
        pred = preds_map.get(rid, "free flowing")
        final_rows.append({"ID": rid, "Target": pred, "Target_Accuracy": pred})
        
    submission = pd.DataFrame(final_rows)
    submission.to_csv('submission_grandmaster.csv', index=False)
    print("SUCCESS: 'submission_grandmaster.csv' generated.")
    print("This submission contains unique predictions for BOTH Enter and Exit ratings.")

if __name__ == "__main__":
    main()